# Generated by Django 4.2.3 on 2023-07-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omac_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnymalType',
            new_name='AnimalType',
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='omac_app.animaltype')),
            ],
        ),
    ]
