# Generated by Django 4.2.3 on 2023-07-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omac_app', '0003_alter_breed_type_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='omac_app.animal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weighting',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_date_constraint'),
        ),
    ]
