# Generated by Django 4.2.3 on 2023-07-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omac_app', '0005_remove_weighting_unique_date_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='arrival_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
