# Generated by Django 4.2.3 on 2023-07-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omac_app', '0006_alter_animal_arrival_age_alter_weighting_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='number',
            new_name='inventory_num',
        ),
    ]
